; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG157258 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG157259 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157260 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG157619 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG157620 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157621 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG157980 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG157981 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG157982 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_QMsgTextEdit@@3Uqt_meta_stringdata_QMsgTextEdit_t@@B DD 0ffffffffH ; qt_meta_stringdata_QMsgTextEdit
	DD	0cH
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	019H
	DD	00H
	ORG $+4
	DQ	0000000000000055H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000057H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000040H
	DB	051H
	DB	04dH
	DB	073H
	DB	067H
	DB	054H
	DB	065H
	DB	078H
	DB	074H
	DB	045H
	DB	064H
	DB	069H
	DB	074H
	DB	00H
	DB	06fH
	DB	06eH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	049H
	DB	06dH
	DB	061H
	DB	067H
	DB	065H
	DB	046H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	00H
	DB	00H
	DB	066H
	DB	072H
	DB	061H
	DB	06dH
	DB	065H
	DB	00H
	ORG $+2
?qt_meta_data_QMsgTextEdit@@3QBIB DD 08H		; qt_meta_data_QMsgTextEdit
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	013H
	DD	02H
	DD	08H
	DD	02bH
	DD	02H
	DD	03H
	DD	00H
	ORG $+4
$SG159205 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG159206 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG159207 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154128 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG154129 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154130 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ ; QMsgTextEdit::metaObject
PUBLIC	?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z	; QMsgTextEdit::qt_metacast
PUBLIC	?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_metacall
PUBLIC	?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QTextEdit::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QTextEdit::staticMetaObject>
PUBLIC	?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B ; QMsgTextEdit::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QTextEdit@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onEmotionImageFrameChange@QMsgTextEdit@@AEAAXH@Z:PROC ; QMsgTextEdit::onEmotionImageFrameChange
EXTRN	__imp_?staticMetaObject@QTextEdit@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B DB 030H DUP (?) ; QMsgTextEdit::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN8
	DD	imagerel $LN8+92
	DD	imagerel $unwind$?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@QMsgTextEdit@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@QMsgTextEdit@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'QMsgTextEdit::staticMetaObject'', COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 87
	sub	rsp, 40					; 00000028H
; Line 81
	lea	rcx, OFFSET FLAT:?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B ; QMsgTextEdit::staticMetaObject
	call	??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QTextEdit::staticMetaObject>
; Line 82
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_QMsgTextEdit@@3Uqt_meta_stringdata_QMsgTextEdit_t@@B
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+8, rax
; Line 83
	lea	rax, OFFSET FLAT:?qt_meta_data_QMsgTextEdit@@3QBIB
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+16, rax
; Line 84
	lea	rax, OFFSET FLAT:?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+24, rax
; Line 85
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+32, 0
; Line 86
	mov	QWORD PTR ?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'QMsgTextEdit::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QTextEdit::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QTextEdit@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QTextEdit::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QTextEdit::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QTextEdit::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QTextEdit@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QTextEdit::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; QMsgTextEdit::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 69
$LN8:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 70
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 71
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 73
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	jmp	SHORT $LN6@qt_static_
$LN5@qt_static_:
; Line 74
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onEmotionImageFrameChange@QMsgTextEdit@@AEAAXH@Z ; QMsgTextEdit::onEmotionImageFrameChange
$LN6@qt_static_:
$LN4@qt_static_:
; Line 78
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QMsgTextEdit::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; QMsgTextEdit::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 104
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 105
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 106
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 107
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 108
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 109
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 110
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@QMsgTextEdit@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; QMsgTextEdit::qt_static_metacall
$LN5@qt_metacal:
; Line 111
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 112
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 113
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 114
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 115
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 117
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 118
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@QMsgTextEdit@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; QMsgTextEdit::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z PROC		; QMsgTextEdit::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 96
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 97
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 98
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_QMsgTextEdit@@3Uqt_meta_stringdata_QMsgTextEdit_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 99
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 100
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QTextEdit@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 101
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@QMsgTextEdit@@UEAAPEAXPEBD@Z ENDP		; QMsgTextEdit::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ PROC	; QMsgTextEdit::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 91
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 92
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@QMsgTextEdit@@2UQMetaObject@@B ; QMsgTextEdit::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 93
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@QMsgTextEdit@@UEBAPEBUQMetaObject@@XZ ENDP	; QMsgTextEdit::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 121
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_qmsgtextedit.cpp
; Line 121
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
