; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_TitleBar@@3Uqt_meta_stringdata_TitleBar_t@@B DD 0ffffffffH ; qt_meta_stringdata_TitleBar
	DD	08H
	DD	00H
	ORG $+4
	DQ	0000000000000090H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	0000000000000081H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000080H
	DD	0ffffffffH
	DD	01aH
	DD	00H
	ORG $+4
	DQ	0000000000000069H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	000000000000006cH
	DD	0ffffffffH
	DD	018H
	DD	00H
	ORG $+4
	DQ	000000000000006bH
	DB	054H
	DB	069H
	DB	074H
	DB	06cH
	DB	065H
	DB	042H
	DB	061H
	DB	072H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	04dH
	DB	069H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	052H
	DB	065H
	DB	073H
	DB	074H
	DB	06fH
	DB	072H
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	04dH
	DB	061H
	DB	078H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	043H
	DB	06cH
	DB	06fH
	DB	073H
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+4
?qt_meta_data_TitleBar@@3QBIB DD 08H			; qt_meta_data_TitleBar
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	01H
	DD	00H
	DD	022H
	DD	02H
	DD	06H
	DD	03H
	DD	00H
	DD	023H
	DD	02H
	DD	06H
	DD	04H
	DD	00H
	DD	024H
	DD	02H
	DD	06H
	DD	05H
	DD	00H
	DD	025H
	DD	02H
	DD	06H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG143726 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG143727 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG143728 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG144087 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG144088 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG144089 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG144448 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG144449 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG144450 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@TitleBar@@UEBAPEBUQMetaObject@@XZ	; TitleBar::metaObject
PUBLIC	?qt_metacast@TitleBar@@UEAAPEAXPEBD@Z		; TitleBar::qt_metacast
PUBLIC	?qt_metacall@TitleBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; TitleBar::qt_metacall
PUBLIC	?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TitleBar::qt_static_metacall
PUBLIC	?signalButtonMinClicked@TitleBar@@QEAAXXZ	; TitleBar::signalButtonMinClicked
PUBLIC	?signalButtonRestoreClicked@TitleBar@@QEAAXXZ	; TitleBar::signalButtonRestoreClicked
PUBLIC	?signalButtonMaxClicked@TitleBar@@QEAAXXZ	; TitleBar::signalButtonMaxClicked
PUBLIC	?signalButtonCloseClicked@TitleBar@@QEAAXXZ	; TitleBar::signalButtonCloseClicked
PUBLIC	??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
PUBLIC	?staticMetaObject@TitleBar@@2UQMetaObject@@B	; TitleBar::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@TitleBar@@2UQMetaObject@@B DB 030H DUP (?) ; TitleBar::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@TitleBar@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@TitleBar@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@TitleBar@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@TitleBar@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@TitleBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@TitleBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN29
	DD	imagerel $LN29+786
	DD	imagerel $unwind$?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?signalButtonMinClicked@TitleBar@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?signalButtonMinClicked@TitleBar@@QEAAXXZ
$pdata$?signalButtonRestoreClicked@TitleBar@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$?signalButtonRestoreClicked@TitleBar@@QEAAXXZ
$pdata$?signalButtonMaxClicked@TitleBar@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$?signalButtonMaxClicked@TitleBar@@QEAAXXZ
$pdata$?signalButtonCloseClicked@TitleBar@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$?signalButtonCloseClicked@TitleBar@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@TitleBar@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@TitleBar@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@TitleBar@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@TitleBar@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@TitleBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 021a01H
	DD	013011aH
$unwind$?signalButtonMinClicked@TitleBar@@QEAAXXZ DD 010901H
	DD	04209H
$unwind$?signalButtonRestoreClicked@TitleBar@@QEAAXXZ DD 010901H
	DD	04209H
$unwind$?signalButtonMaxClicked@TitleBar@@QEAAXXZ DD 010901H
	DD	04209H
$unwind$?signalButtonCloseClicked@TitleBar@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'TitleBar::staticMetaObject'', COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 130
	sub	rsp, 40					; 00000028H
; Line 124
	lea	rcx, OFFSET FLAT:?staticMetaObject@TitleBar@@2UQMetaObject@@B ; TitleBar::staticMetaObject
	call	??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
; Line 125
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_TitleBar@@3Uqt_meta_stringdata_TitleBar_t@@B
	mov	QWORD PTR ?staticMetaObject@TitleBar@@2UQMetaObject@@B+8, rax
; Line 126
	lea	rax, OFFSET FLAT:?qt_meta_data_TitleBar@@3QBIB
	mov	QWORD PTR ?staticMetaObject@TitleBar@@2UQMetaObject@@B+16, rax
; Line 127
	lea	rax, OFFSET FLAT:?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TitleBar::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@TitleBar@@2UQMetaObject@@B+24, rax
; Line 128
	mov	QWORD PTR ?staticMetaObject@TitleBar@@2UQMetaObject@@B+32, 0
; Line 129
	mov	QWORD PTR ?staticMetaObject@TitleBar@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@TitleBar@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'TitleBar::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?signalButtonCloseClicked@TitleBar@@QEAAXXZ PROC	; TitleBar::signalButtonCloseClicked
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 183
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 184
	xor	r9d, r9d
	mov	r8d, 3
	lea	rdx, OFFSET FLAT:?staticMetaObject@TitleBar@@2UQMetaObject@@B ; TitleBar::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 185
	add	rsp, 40					; 00000028H
	ret	0
?signalButtonCloseClicked@TitleBar@@QEAAXXZ ENDP	; TitleBar::signalButtonCloseClicked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?signalButtonMaxClicked@TitleBar@@QEAAXXZ PROC		; TitleBar::signalButtonMaxClicked
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 177
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 178
	xor	r9d, r9d
	mov	r8d, 2
	lea	rdx, OFFSET FLAT:?staticMetaObject@TitleBar@@2UQMetaObject@@B ; TitleBar::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 179
	add	rsp, 40					; 00000028H
	ret	0
?signalButtonMaxClicked@TitleBar@@QEAAXXZ ENDP		; TitleBar::signalButtonMaxClicked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?signalButtonRestoreClicked@TitleBar@@QEAAXXZ PROC	; TitleBar::signalButtonRestoreClicked
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 171
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 172
	xor	r9d, r9d
	mov	r8d, 1
	lea	rdx, OFFSET FLAT:?staticMetaObject@TitleBar@@2UQMetaObject@@B ; TitleBar::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 173
	add	rsp, 40					; 00000028H
	ret	0
?signalButtonRestoreClicked@TitleBar@@QEAAXXZ ENDP	; TitleBar::signalButtonRestoreClicked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
?signalButtonMinClicked@TitleBar@@QEAAXXZ PROC		; TitleBar::signalButtonMinClicked
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 165
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 166
	xor	r9d, r9d
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@TitleBar@@2UQMetaObject@@B ; TitleBar::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 167
	add	rsp, 40					; 00000028H
	ret	0
?signalButtonMinClicked@TitleBar@@QEAAXXZ ENDP		; TitleBar::signalButtonMinClicked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
tv93 = 36
tv139 = 40
tv153 = 44
tv167 = 48
_t$1 = 56
result$2 = 64
$T3 = 72
$T4 = 88
$T5 = 104
$T6 = 120
_o$ = 160
_c$ = 168
_id$ = 176
_a$ = 184
?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; TitleBar::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 78
$LN29:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 152				; 00000098H
; Line 79
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 80
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 82
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN8@qt_static_
	cmp	DWORD PTR tv69[rsp], 3
	je	SHORT $LN9@qt_static_
	jmp	SHORT $LN10@qt_static_
$LN6@qt_static_:
; Line 83
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalButtonMinClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonMinClicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 84
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalButtonRestoreClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonRestoreClicked
	jmp	SHORT $LN2@qt_static_
$LN8@qt_static_:
; Line 85
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalButtonMaxClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonMaxClicked
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 86
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalButtonCloseClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonCloseClicked
$LN10@qt_static_:
$LN2@qt_static_:
; Line 89
	jmp	$LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	$LN11@qt_static_
; Line 90
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 93
	lea	rax, OFFSET FLAT:?signalButtonMinClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonMinClicked
	mov	QWORD PTR $T3[rsp], rax
	mov	DWORD PTR $T3[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T3[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN18@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN17@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T3[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN18@qt_static_
$LN17@qt_static_:
	mov	DWORD PTR tv93[rsp], 1
	jmp	SHORT $LN19@qt_static_
$LN18@qt_static_:
	mov	DWORD PTR tv93[rsp], 0
$LN19@qt_static_:
	cmp	DWORD PTR tv93[rsp], 0
	je	SHORT $LN12@qt_static_
; Line 94
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
; Line 95
	jmp	$LN1@qt_static_
$LN12@qt_static_:
; Line 100
	lea	rax, OFFSET FLAT:?signalButtonRestoreClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonRestoreClicked
	mov	QWORD PTR $T4[rsp], rax
	mov	DWORD PTR $T4[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T4[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN21@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN20@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T4[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN21@qt_static_
$LN20@qt_static_:
	mov	DWORD PTR tv139[rsp], 1
	jmp	SHORT $LN22@qt_static_
$LN21@qt_static_:
	mov	DWORD PTR tv139[rsp], 0
$LN22@qt_static_:
	cmp	DWORD PTR tv139[rsp], 0
	je	SHORT $LN13@qt_static_
; Line 101
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 1
; Line 102
	jmp	$LN1@qt_static_
$LN13@qt_static_:
; Line 107
	lea	rax, OFFSET FLAT:?signalButtonMaxClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonMaxClicked
	mov	QWORD PTR $T5[rsp], rax
	mov	DWORD PTR $T5[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T5[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN24@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN23@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T5[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN24@qt_static_
$LN23@qt_static_:
	mov	DWORD PTR tv153[rsp], 1
	jmp	SHORT $LN25@qt_static_
$LN24@qt_static_:
	mov	DWORD PTR tv153[rsp], 0
$LN25@qt_static_:
	cmp	DWORD PTR tv153[rsp], 0
	je	SHORT $LN14@qt_static_
; Line 108
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 2
; Line 109
	jmp	$LN1@qt_static_
$LN14@qt_static_:
; Line 114
	lea	rax, OFFSET FLAT:?signalButtonCloseClicked@TitleBar@@QEAAXXZ ; TitleBar::signalButtonCloseClicked
	mov	QWORD PTR $T6[rsp], rax
	mov	DWORD PTR $T6[rsp+8], 0
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR $T6[rsp]
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN27@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	cmp	QWORD PTR [rax], 0
	je	SHORT $LN26@qt_static_
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	ecx, DWORD PTR $T6[rsp+8]
	cmp	DWORD PTR [rax+8], ecx
	jne	SHORT $LN27@qt_static_
$LN26@qt_static_:
	mov	DWORD PTR tv167[rsp], 1
	jmp	SHORT $LN28@qt_static_
$LN27@qt_static_:
	mov	DWORD PTR tv167[rsp], 0
$LN28@qt_static_:
	cmp	DWORD PTR tv167[rsp], 0
	je	SHORT $LN15@qt_static_
; Line 115
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 3
$LN15@qt_static_:
$LN11@qt_static_:
$LN5@qt_static_:
$LN1@qt_static_:
; Line 121
	add	rsp, 152				; 00000098H
	ret	0
?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TitleBar::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@TitleBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; TitleBar::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 147
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 148
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 149
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 150
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 151
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 152
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN5@qt_metacal
; Line 153
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@TitleBar@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TitleBar::qt_static_metacall
$LN5@qt_metacal:
; Line 154
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 155
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 156
	cmp	DWORD PTR _id$[rsp], 4
	jge	SHORT $LN7@qt_metacal
; Line 157
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 158
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 4
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 160
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 161
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@TitleBar@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TitleBar::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@TitleBar@@UEAAPEAXPEBD@Z PROC		; TitleBar::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 139
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 140
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 141
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_TitleBar@@3Uqt_meta_stringdata_TitleBar_t@@B+144
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 142
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 143
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 144
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@TitleBar@@UEAAPEAXPEBD@Z ENDP		; TitleBar::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@TitleBar@@UEBAPEBUQMetaObject@@XZ PROC	; TitleBar::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 134
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 135
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@TitleBar@@2UQMetaObject@@B ; TitleBar::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 136
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@TitleBar@@UEBAPEBUQMetaObject@@XZ ENDP	; TitleBar::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 188
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_titlebar.cpp
; Line 188
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
