; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?staticMetaObject@TalkWindowShell@@2UQMetaObject@@B ; TalkWindowShell::staticMetaObject
PUBLIC	?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindowShell::qt_static_metacall
EXTRN	?staticMetaObject@BasicWindow@@2UQMetaObject@@B:BYTE ; BasicWindow::staticMetaObject
CONST	SEGMENT
$SG181103 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG181104 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG181105 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG181464 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG181465 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG181466 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG181825 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG181826 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG181827 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG182293 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG182294 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG182295 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG175927 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG175928 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG175929 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?staticMetaObject@TalkWindowShell@@2UQMetaObject@@B DQ FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; TalkWindowShell::staticMetaObject
	DQ	FLAT:?qt_meta_stringdata_TalkWindowShell@@3Uqt_meta_stringdata_TalkWindowShell_t@@B
	DQ	FLAT:?qt_meta_data_TalkWindowShell@@3QBIB
	DQ	FLAT:?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
	DQ	0000000000000000H
	DQ	0000000000000000H
$SG179211 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG179212 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179213 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_TalkWindowShell@@3Uqt_meta_stringdata_TalkWindowShell_t@@B DD 0ffffffffH ; qt_meta_stringdata_TalkWindowShell
	DD	0fH
	DD	00H
	ORG $+4
	DQ	00000000000000c0H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000000b8H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	00000000000000b4H
	DD	0ffffffffH
	DD	017H
	DD	00H
	ORG $+4
	DQ	000000000000009dH
	DD	0ffffffffH
	DD	010H
	DD	00H
	ORG $+4
	DQ	000000000000009dH
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	0000000000000096H
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000083H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000080H
	DB	054H
	DB	061H
	DB	06cH
	DB	06bH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	053H
	DB	068H
	DB	065H
	DB	06cH
	DB	06cH
	DB	00H
	DB	06fH
	DB	06eH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	042H
	DB	074H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	054H
	DB	061H
	DB	06cH
	DB	06bH
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	051H
	DB	04cH
	DB	069H
	DB	073H
	DB	074H
	DB	057H
	DB	069H
	DB	064H
	DB	067H
	DB	065H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	02aH
	DB	00H
	DB	069H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	DB	06fH
	DB	06eH
	DB	045H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	065H
	DB	06dH
	DB	06fH
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	04eH
	DB	075H
	DB	06dH
	DB	00H
	ORG $+5
	ORG $+8
?qt_meta_data_TalkWindowShell@@3QBIB DD 08H		; qt_meta_data_TalkWindowShell
	DD	00H
	DD	00H
	DD	00H
	DD	03H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	01dH
	DD	02H
	DD	0aH
	DD	03H
	DD	01H
	DD	020H
	DD	02H
	DD	08H
	DD	06H
	DD	01H
	DD	023H
	DD	02H
	DD	08H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	080000004H
	DD	05H
	DD	02bH
	DD	02H
	DD	07H
	DD	00H
	ORG $+4
$SG179572 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG179573 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179574 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG179933 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG179934 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG179935 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ ; TalkWindowShell::metaObject
PUBLIC	?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z	; TalkWindowShell::qt_metacast
PUBLIC	?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindowShell::qt_metacall
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z:PROC	; BasicWindow::qt_metacast
EXTRN	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC ; BasicWindow::qt_metacall
EXTRN	?onEmotionBtnClicked@TalkWindowShell@@QEAAX_N@Z:PROC ; TalkWindowShell::onEmotionBtnClicked
EXTRN	?onTalkWindowItemClicked@TalkWindowShell@@AEAAXPEAVQListWidgetItem@@@Z:PROC ; TalkWindowShell::onTalkWindowItemClicked
EXTRN	?onEmotionItemClicked@TalkWindowShell@@AEAAXH@Z:PROC ; TalkWindowShell::onEmotionItemClicked
pdata	SEGMENT
$pdata$?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+74
	DD	imagerel $unwind$?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+173
	DD	imagerel $unwind$?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN10
	DD	imagerel $LN10+176
	DD	imagerel $unwind$?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; TalkWindowShell::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 78
$LN10:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 79
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 80
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 82
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	cmp	DWORD PTR tv69[rsp], 2
	je	SHORT $LN7@qt_static_
	jmp	SHORT $LN8@qt_static_
$LN5@qt_static_:
; Line 83
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onEmotionBtnClicked@TalkWindowShell@@QEAAX_N@Z ; TalkWindowShell::onEmotionBtnClicked
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 84
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onTalkWindowItemClicked@TalkWindowShell@@AEAAXPEAVQListWidgetItem@@@Z ; TalkWindowShell::onTalkWindowItemClicked
	jmp	SHORT $LN2@qt_static_
$LN7@qt_static_:
; Line 85
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onEmotionItemClicked@TalkWindowShell@@AEAAXH@Z ; TalkWindowShell::onEmotionItemClicked
$LN8@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 89
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TalkWindowShell::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; TalkWindowShell::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 115
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 116
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_metacall
	mov	DWORD PTR _id$[rsp], eax
; Line 117
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 118
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 119
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 120
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN5@qt_metacal
; Line 121
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@TalkWindowShell@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; TalkWindowShell::qt_static_metacall
$LN5@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 123
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 124
	cmp	DWORD PTR _id$[rsp], 3
	jge	SHORT $LN7@qt_metacal
; Line 125
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 126
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 3
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 128
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 129
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@TalkWindowShell@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; TalkWindowShell::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z PROC	; TalkWindowShell::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 107
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 108
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 109
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_TalkWindowShell@@3Uqt_meta_stringdata_TalkWindowShell_t@@B+192
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 110
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 111
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z ; BasicWindow::qt_metacast
$LN1@qt_metacas:
; Line 112
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@TalkWindowShell@@UEAAPEAXPEBD@Z ENDP	; TalkWindowShell::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ PROC ; TalkWindowShell::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 102
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 103
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@TalkWindowShell@@2UQMetaObject@@B ; TalkWindowShell::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 104
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@TalkWindowShell@@UEBAPEBUQMetaObject@@XZ ENDP ; TalkWindowShell::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 132
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_talkwindowshell.cpp
; Line 132
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
