; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_SysTray@@3Uqt_meta_stringdata_SysTray_t@@B DD 0ffffffffH ; qt_meta_stringdata_SysTray
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	ORG $+4
	DQ	0000000000000068H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	021H
	DD	00H
	ORG $+4
	DQ	0000000000000049H
	DD	0ffffffffH
	DD	06H
	DD	00H
	ORG $+4
	DQ	0000000000000053H
	DB	053H
	DB	079H
	DB	073H
	DB	054H
	DB	072H
	DB	061H
	DB	079H
	DB	00H
	DB	06fH
	DB	06eH
	DB	049H
	DB	063H
	DB	06fH
	DB	06eH
	DB	041H
	DB	063H
	DB	074H
	DB	069H
	DB	076H
	DB	061H
	DB	074H
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	051H
	DB	053H
	DB	079H
	DB	073H
	DB	074H
	DB	065H
	DB	06dH
	DB	054H
	DB	072H
	DB	061H
	DB	079H
	DB	049H
	DB	063H
	DB	06fH
	DB	06eH
	DB	03aH
	DB	03aH
	DB	041H
	DB	063H
	DB	074H
	DB	069H
	DB	076H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	052H
	DB	065H
	DB	061H
	DB	073H
	DB	06fH
	DB	06eH
	DB	00H
	DB	072H
	DB	065H
	DB	061H
	DB	073H
	DB	06fH
	DB	06eH
	DB	00H
	ORG $+6
?qt_meta_data_SysTray@@3QBIB DD 08H			; qt_meta_data_SysTray
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	013H
	DD	02H
	DD	0aH
	DD	02bH
	DD	080000003H
	DD	04H
	DD	00H
	ORG $+4
$SG143121 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG143122 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG143123 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG143482 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG143483 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG143484 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG143843 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG143844 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG143845 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@SysTray@@UEBAPEBUQMetaObject@@XZ	; SysTray::metaObject
PUBLIC	?qt_metacast@SysTray@@UEAAPEAXPEBD@Z		; SysTray::qt_metacast
PUBLIC	?qt_metacall@SysTray@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; SysTray::qt_metacall
PUBLIC	?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SysTray::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QSystemTrayIcon::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QSystemTrayIcon::staticMetaObject>
PUBLIC	?staticMetaObject@SysTray@@2UQMetaObject@@B	; SysTray::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QSystemTrayIcon@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QSystemTrayIcon@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onIconActivated@SysTray@@QEAAXW4ActivationReason@QSystemTrayIcon@@@Z:PROC ; SysTray::onIconActivated
EXTRN	__imp_?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@SysTray@@2UQMetaObject@@B DB 030H DUP (?) ; SysTray::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@SysTray@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@SysTray@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@SysTray@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@SysTray@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@SysTray@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@SysTray@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN8
	DD	imagerel $LN8+92
	DD	imagerel $unwind$?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@SysTray@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@SysTray@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@SysTray@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@SysTray@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@SysTray@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'SysTray::staticMetaObject'', COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 89
	sub	rsp, 40					; 00000028H
; Line 83
	lea	rcx, OFFSET FLAT:?staticMetaObject@SysTray@@2UQMetaObject@@B ; SysTray::staticMetaObject
	call	??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QSystemTrayIcon::staticMetaObject>
; Line 84
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_SysTray@@3Uqt_meta_stringdata_SysTray_t@@B
	mov	QWORD PTR ?staticMetaObject@SysTray@@2UQMetaObject@@B+8, rax
; Line 85
	lea	rax, OFFSET FLAT:?qt_meta_data_SysTray@@3QBIB
	mov	QWORD PTR ?staticMetaObject@SysTray@@2UQMetaObject@@B+16, rax
; Line 86
	lea	rax, OFFSET FLAT:?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SysTray::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@SysTray@@2UQMetaObject@@B+24, rax
; Line 87
	mov	QWORD PTR ?staticMetaObject@SysTray@@2UQMetaObject@@B+32, 0
; Line 88
	mov	QWORD PTR ?staticMetaObject@SysTray@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@SysTray@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'SysTray::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QSystemTrayIcon::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QSystemTrayIcon::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QSystemTrayIcon::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QSystemTrayIcon::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QSystemTrayIcon@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QSystemTrayIcon::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; SysTray::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 71
$LN8:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 72
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 73
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 75
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	jmp	SHORT $LN6@qt_static_
$LN5@qt_static_:
; Line 76
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	edx, DWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onIconActivated@SysTray@@QEAAXW4ActivationReason@QSystemTrayIcon@@@Z ; SysTray::onIconActivated
$LN6@qt_static_:
$LN4@qt_static_:
; Line 80
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; SysTray::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@SysTray@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; SysTray::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 106
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 107
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QSystemTrayIcon@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 108
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 109
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 110
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 111
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 112
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@SysTray@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; SysTray::qt_static_metacall
$LN5@qt_metacal:
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 114
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 115
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 116
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 117
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 120
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@SysTray@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; SysTray::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@SysTray@@UEAAPEAXPEBD@Z PROC		; SysTray::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 98
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 99
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 100
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_SysTray@@3Uqt_meta_stringdata_SysTray_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 101
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 102
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QSystemTrayIcon@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 103
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@SysTray@@UEAAPEAXPEBD@Z ENDP		; SysTray::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@SysTray@@UEBAPEBUQMetaObject@@XZ PROC	; SysTray::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 93
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 94
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@SysTray@@2UQMetaObject@@B ; SysTray::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 95
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@SysTray@@UEBAPEBUQMetaObject@@XZ ENDP	; SysTray::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 123
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_systray.cpp
; Line 123
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
