; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG151102 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG151103 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG151104 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154184 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG154185 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154186 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154545 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG154546 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154547 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG154906 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG154907 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG154908 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_ContactItem@@3Uqt_meta_stringdata_ContactItem_t@@B DD 0ffffffffH ; qt_meta_stringdata_ContactItem
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	043H
	DB	06fH
	DB	06eH
	DB	074H
	DB	061H
	DB	063H
	DB	074H
	DB	049H
	DB	074H
	DB	065H
	DB	06dH
	DB	00H
	ORG $+4
?qt_meta_data_ContactItem@@3QBIB DD 08H			; qt_meta_data_ContactItem
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@ContactItem@@UEBAPEBUQMetaObject@@XZ ; ContactItem::metaObject
PUBLIC	?qt_metacast@ContactItem@@UEAAPEAXPEBD@Z	; ContactItem::qt_metacast
PUBLIC	?qt_metacall@ContactItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; ContactItem::qt_metacall
PUBLIC	?qt_static_metacall@ContactItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; ContactItem::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
PUBLIC	?staticMetaObject@ContactItem@@2UQMetaObject@@B	; ContactItem::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@ContactItem@@2UQMetaObject@@B DB 030H DUP (?) ; ContactItem::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@ContactItem@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@ContactItem@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@ContactItem@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@ContactItem@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@ContactItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?qt_metacall@ContactItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@ContactItem@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@ContactItem@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@ContactItem@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@ContactItem@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@ContactItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'ContactItem::staticMetaObject'', COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 73
	sub	rsp, 40					; 00000028H
; Line 67
	lea	rcx, OFFSET FLAT:?staticMetaObject@ContactItem@@2UQMetaObject@@B ; ContactItem::staticMetaObject
	call	??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_ContactItem@@3Uqt_meta_stringdata_ContactItem_t@@B
	mov	QWORD PTR ?staticMetaObject@ContactItem@@2UQMetaObject@@B+8, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_meta_data_ContactItem@@3QBIB
	mov	QWORD PTR ?staticMetaObject@ContactItem@@2UQMetaObject@@B+16, rax
; Line 70
	lea	rax, OFFSET FLAT:?qt_static_metacall@ContactItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; ContactItem::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@ContactItem@@2UQMetaObject@@B+24, rax
; Line 71
	mov	QWORD PTR ?staticMetaObject@ContactItem@@2UQMetaObject@@B+32, 0
; Line 72
	mov	QWORD PTR ?staticMetaObject@ContactItem@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@ContactItem@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'ContactItem::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QWidget::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QWidget@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QWidget::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@ContactItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; ContactItem::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 59
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 64
	ret	0
?qt_static_metacall@ContactItem@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; ContactItem::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@ContactItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; ContactItem::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 90
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 91
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 92
	mov	eax, DWORD PTR _id$[rsp]
; Line 93
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@ContactItem@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; ContactItem::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@ContactItem@@UEAAPEAXPEBD@Z PROC		; ContactItem::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 82
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 83
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 84
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_ContactItem@@3Uqt_meta_stringdata_ContactItem_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 85
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 86
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 87
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@ContactItem@@UEAAPEAXPEBD@Z ENDP		; ContactItem::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@ContactItem@@UEBAPEBUQMetaObject@@XZ PROC	; ContactItem::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 77
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 78
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@ContactItem@@2UQMetaObject@@B ; ContactItem::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 79
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@ContactItem@@UEBAPEBUQMetaObject@@XZ ENDP	; ContactItem::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 96
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_contactitem.cpp
; Line 96
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
