; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_BasicWindow@@3Uqt_meta_stringdata_BasicWindow_t@@B DD 0ffffffffH ; qt_meta_stringdata_BasicWindow
	DD	0bH
	DD	00H
	ORG $+4
	DQ	0000000000000138H
	DD	0ffffffffH
	DD	0bH
	DD	00H
	ORG $+4
	DQ	000000000000012cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000120H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	0000000000000109H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000000fbH
	DD	0ffffffffH
	DD	0cH
	DD	00H
	ORG $+4
	DQ	00000000000000eeH
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	00000000000000e3H
	DD	0ffffffffH
	DD	013H
	DD	00H
	ORG $+4
	DQ	00000000000000d6H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	00000000000000d2H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000c0H
	DD	0ffffffffH
	DD	016H
	DD	00H
	ORG $+4
	DQ	00000000000000bbH
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000baH
	DD	0ffffffffH
	DD	014H
	DD	00H
	ORG $+4
	DQ	00000000000000b5H
	DB	042H
	DB	061H
	DB	073H
	DB	069H
	DB	063H
	DB	057H
	DB	069H
	DB	06eH
	DB	064H
	DB	06fH
	DB	077H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	068H
	DB	06fH
	DB	077H
	DB	043H
	DB	06cH
	DB	06fH
	DB	073H
	DB	065H
	DB	00H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	068H
	DB	06fH
	DB	077H
	DB	04dH
	DB	069H
	DB	06eH
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	068H
	DB	06fH
	DB	077H
	DB	048H
	DB	069H
	DB	064H
	DB	065H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	068H
	DB	06fH
	DB	077H
	DB	04eH
	DB	06fH
	DB	072H
	DB	06dH
	DB	061H
	DB	06cH
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	068H
	DB	06fH
	DB	077H
	DB	051H
	DB	075H
	DB	069H
	DB	074H
	DB	00H
	DB	06fH
	DB	06eH
	DB	053H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	053H
	DB	06bH
	DB	069H
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	063H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	00H
	DB	06fH
	DB	06eH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	04dH
	DB	069H
	DB	06eH
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	052H
	DB	065H
	DB	073H
	DB	074H
	DB	06fH
	DB	072H
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	04dH
	DB	061H
	DB	078H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	06eH
	DB	042H
	DB	075H
	DB	074H
	DB	074H
	DB	06fH
	DB	06eH
	DB	043H
	DB	06cH
	DB	06fH
	DB	073H
	DB	065H
	DB	043H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+6
?qt_meta_data_BasicWindow@@3QBIB DD 08H			; qt_meta_data_BasicWindow
	DD	00H
	DD	00H
	DD	00H
	DD	0aH
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	040H
	DD	02H
	DD	0aH
	DD	03H
	DD	01H
	DD	043H
	DD	02H
	DD	0aH
	DD	04H
	DD	01H
	DD	046H
	DD	02H
	DD	0aH
	DD	05H
	DD	01H
	DD	049H
	DD	02H
	DD	0aH
	DD	06H
	DD	01H
	DD	04cH
	DD	02H
	DD	0aH
	DD	07H
	DD	01H
	DD	04fH
	DD	02H
	DD	0aH
	DD	09H
	DD	00H
	DD	052H
	DD	02H
	DD	0aH
	DD	0aH
	DD	00H
	DD	053H
	DD	02H
	DD	0aH
	DD	0bH
	DD	00H
	DD	054H
	DD	02H
	DD	0aH
	DD	0cH
	DD	00H
	DD	055H
	DD	02H
	DD	0aH
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	01H
	DD	02H
	DD	02bH
	DD	043H
	DD	08H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
	ORG $+4
$SG143878 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG143879 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG143880 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG144239 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG144240 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG144241 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG144600 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG144601 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG144602 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@BasicWindow@@UEBAPEBUQMetaObject@@XZ ; BasicWindow::metaObject
PUBLIC	?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z	; BasicWindow::qt_metacast
PUBLIC	?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_metacall
PUBLIC	?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_static_metacall
PUBLIC	??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QDialog::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>
PUBLIC	?staticMetaObject@BasicWindow@@2UQMetaObject@@B	; BasicWindow::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?onShowClose@BasicWindow@@QEAAX_N@Z:PROC	; BasicWindow::onShowClose
EXTRN	?onShowMin@BasicWindow@@QEAAX_N@Z:PROC		; BasicWindow::onShowMin
EXTRN	?onShowHide@BasicWindow@@QEAAX_N@Z:PROC		; BasicWindow::onShowHide
EXTRN	?onShowNormal@BasicWindow@@QEAAX_N@Z:PROC	; BasicWindow::onShowNormal
EXTRN	?onShowQuit@BasicWindow@@QEAAX_N@Z:PROC		; BasicWindow::onShowQuit
EXTRN	?onSignalSkinChanged@BasicWindow@@QEAAXAEBVQColor@@@Z:PROC ; BasicWindow::onSignalSkinChanged
EXTRN	?onButtonMinClicked@BasicWindow@@QEAAXXZ:PROC	; BasicWindow::onButtonMinClicked
EXTRN	?onButtonRestoreClicked@BasicWindow@@QEAAXXZ:PROC ; BasicWindow::onButtonRestoreClicked
EXTRN	?onButtonMaxClicked@BasicWindow@@QEAAXXZ:PROC	; BasicWindow::onButtonMaxClicked
EXTRN	?onButtonCloseClicked@BasicWindow@@QEAAXXZ:PROC	; BasicWindow::onButtonCloseClicked
EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
EXTRN	__ImageBase:BYTE
_BSS	SEGMENT
?staticMetaObject@BasicWindow@@2UQMetaObject@@B DB 030H DUP (?) ; BasicWindow::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@BasicWindow@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@BasicWindow@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN18
	DD	imagerel $LN18+384
	DD	imagerel $unwind$?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@BasicWindow@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@BasicWindow@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@BasicWindow@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'BasicWindow::staticMetaObject'', COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 126
	sub	rsp, 40					; 00000028H
; Line 120
	lea	rcx, OFFSET FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; BasicWindow::staticMetaObject
	call	??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QDialog::staticMetaObject>
; Line 121
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_BasicWindow@@3Uqt_meta_stringdata_BasicWindow_t@@B
	mov	QWORD PTR ?staticMetaObject@BasicWindow@@2UQMetaObject@@B+8, rax
; Line 122
	lea	rax, OFFSET FLAT:?qt_meta_data_BasicWindow@@3QBIB
	mov	QWORD PTR ?staticMetaObject@BasicWindow@@2UQMetaObject@@B+16, rax
; Line 123
	lea	rax, OFFSET FLAT:?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@BasicWindow@@2UQMetaObject@@B+24, rax
; Line 124
	mov	QWORD PTR ?staticMetaObject@BasicWindow@@2UQMetaObject@@B+32, 0
; Line 125
	mov	QWORD PTR ?staticMetaObject@BasicWindow@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@BasicWindow@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'BasicWindow::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QDialog::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QDialog::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QDialog@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QDialog::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; BasicWindow::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 99
$LN18:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 100
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 101
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 103
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 9
	ja	$LN15@qt_static_
	movsxd	rax, DWORD PTR tv69[rsp]
	lea	rcx, OFFSET FLAT:__ImageBase
	mov	eax, DWORD PTR $LN17@qt_static_[rcx+rax*4]
	add	rax, rcx
	jmp	rax
$LN5@qt_static_:
; Line 104
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onShowClose@BasicWindow@@QEAAX_N@Z	; BasicWindow::onShowClose
	jmp	$LN2@qt_static_
$LN6@qt_static_:
; Line 105
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onShowMin@BasicWindow@@QEAAX_N@Z	; BasicWindow::onShowMin
	jmp	$LN2@qt_static_
$LN7@qt_static_:
; Line 106
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onShowHide@BasicWindow@@QEAAX_N@Z	; BasicWindow::onShowHide
	jmp	$LN2@qt_static_
$LN8@qt_static_:
; Line 107
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onShowNormal@BasicWindow@@QEAAX_N@Z	; BasicWindow::onShowNormal
	jmp	SHORT $LN2@qt_static_
$LN9@qt_static_:
; Line 108
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	movzx	edx, BYTE PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onShowQuit@BasicWindow@@QEAAX_N@Z	; BasicWindow::onShowQuit
	jmp	SHORT $LN2@qt_static_
$LN10@qt_static_:
; Line 109
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onSignalSkinChanged@BasicWindow@@QEAAXAEBVQColor@@@Z ; BasicWindow::onSignalSkinChanged
	jmp	SHORT $LN2@qt_static_
$LN11@qt_static_:
; Line 110
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonMinClicked@BasicWindow@@QEAAXXZ ; BasicWindow::onButtonMinClicked
	jmp	SHORT $LN2@qt_static_
$LN12@qt_static_:
; Line 111
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonRestoreClicked@BasicWindow@@QEAAXXZ ; BasicWindow::onButtonRestoreClicked
	jmp	SHORT $LN2@qt_static_
$LN13@qt_static_:
; Line 112
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonMaxClicked@BasicWindow@@QEAAXXZ ; BasicWindow::onButtonMaxClicked
	jmp	SHORT $LN2@qt_static_
$LN14@qt_static_:
; Line 113
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?onButtonCloseClicked@BasicWindow@@QEAAXXZ ; BasicWindow::onButtonCloseClicked
$LN15@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 117
	add	rsp, 56					; 00000038H
	ret	0
	npad	2
$LN17@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
	DD	$LN10@qt_static_
	DD	$LN11@qt_static_
	DD	$LN12@qt_static_
	DD	$LN13@qt_static_
	DD	$LN14@qt_static_
?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; BasicWindow::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; BasicWindow::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 143
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 144
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QDialog@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 145
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 146
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 147
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 148
	cmp	DWORD PTR _id$[rsp], 10
	jge	SHORT $LN5@qt_metacal
; Line 149
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@BasicWindow@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; BasicWindow::qt_static_metacall
$LN5@qt_metacal:
; Line 150
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 10
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 151
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 152
	cmp	DWORD PTR _id$[rsp], 10
	jge	SHORT $LN7@qt_metacal
; Line 153
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 154
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 10
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 156
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 157
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@BasicWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; BasicWindow::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z PROC		; BasicWindow::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 135
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 136
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 137
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_BasicWindow@@3Uqt_meta_stringdata_BasicWindow_t@@B+312
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 138
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 139
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QDialog@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 140
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@BasicWindow@@UEAAPEAXPEBD@Z ENDP		; BasicWindow::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@BasicWindow@@UEBAPEBUQMetaObject@@XZ PROC	; BasicWindow::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 130
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 131
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@BasicWindow@@2UQMetaObject@@B ; BasicWindow::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 132
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@BasicWindow@@UEBAPEBUQMetaObject@@XZ ENDP	; BasicWindow::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 160
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_basicwindow.cpp
; Line 160
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
