; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27051.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG123086 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG123087 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG123088 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG123447 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG123448 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG123449 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG123808 DB	'd:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qmetaty'
	DB	'pe.h', 00H
	ORG $+3
$SG123809 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG123810 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_NotifyManager@@3Uqt_meta_stringdata_NotifyManager_t@@B DD 0ffffffffH ; qt_meta_stringdata_NotifyManager
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000060H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000056H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000050H
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000039H
	DB	04eH
	DB	06fH
	DB	074H
	DB	069H
	DB	066H
	DB	079H
	DB	04dH
	DB	061H
	DB	06eH
	DB	061H
	DB	067H
	DB	065H
	DB	072H
	DB	00H
	DB	073H
	DB	069H
	DB	067H
	DB	06eH
	DB	061H
	DB	06cH
	DB	053H
	DB	06bH
	DB	069H
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	00H
	DB	063H
	DB	06fH
	DB	06cH
	DB	06fH
	DB	072H
	DB	00H
	ORG $+1
	ORG $+8
?qt_meta_data_NotifyManager@@3QBIB DD 08H		; qt_meta_data_NotifyManager
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	01H
	DD	013H
	DD	02H
	DD	06H
	DD	02bH
	DD	043H
	DD	03H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z		; QMetaObject::SuperData::SuperData
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@NotifyManager@@UEBAPEBUQMetaObject@@XZ ; NotifyManager::metaObject
PUBLIC	?qt_metacast@NotifyManager@@UEAAPEAXPEBD@Z	; NotifyManager::qt_metacast
PUBLIC	?qt_metacall@NotifyManager@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; NotifyManager::qt_metacall
PUBLIC	?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; NotifyManager::qt_static_metacall
PUBLIC	?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z ; NotifyManager::signalSkinChanged
PUBLIC	??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QObject::staticMetaObject>
PUBLIC	??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>
PUBLIC	??$addressof@$$CBVQColor@@@std@@YAPEBVQColor@@AEBV1@@Z ; std::addressof<QColor const >
PUBLIC	?staticMetaObject@NotifyManager@@2UQMetaObject@@B ; NotifyManager::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QObject@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@NotifyManager@@2UQMetaObject@@B DB 030H DUP (?) ; NotifyManager::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@NotifyManager@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@NotifyManager@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@NotifyManager@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@NotifyManager@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@NotifyManager@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+172
	DD	imagerel $unwind$?qt_metacall@NotifyManager@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN11
	DD	imagerel $LN11+163
	DD	imagerel $unwind$?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z DD imagerel $LN3
	DD	imagerel $LN3+69
	DD	imagerel $unwind$?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD imagerel $LN3
	DD	imagerel $LN3+37
	DD	imagerel $unwind$??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ DD imagerel ??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ
	DD	imagerel ??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ+85
	DD	imagerel $unwind$??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@NotifyManager@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@NotifyManager@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ DD 010901H
	DD	04209H
xdata	ENDS
xdata	SEGMENT
$unwind$?metaObject@NotifyManager@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@NotifyManager@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@NotifyManager@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	08217H
$unwind$?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z DD 010e01H
	DD	0620eH
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$addressof@$$CBVQColor@@@std@@YAPEBVQColor@@AEBV1@@Z
_TEXT	SEGMENT
_Val$ = 8
??$addressof@$$CBVQColor@@@std@@YAPEBVQColor@@AEBV1@@Z PROC ; std::addressof<QColor const >, COMDAT
; File d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xstddef
; Line 329
	mov	QWORD PTR [rsp+8], rcx
; Line 330
	mov	rax, QWORD PTR _Val$[rsp]
; Line 331
	ret	0
??$addressof@$$CBVQColor@@@std@@YAPEBVQColor@@AEBV1@@Z ENDP ; std::addressof<QColor const >
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'NotifyManager::staticMetaObject'', COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 95
	sub	rsp, 40					; 00000028H
; Line 89
	lea	rcx, OFFSET FLAT:?staticMetaObject@NotifyManager@@2UQMetaObject@@B ; NotifyManager::staticMetaObject
	call	??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ; QMetaObject::SuperData::link<&QObject::staticMetaObject>
; Line 90
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_NotifyManager@@3Uqt_meta_stringdata_NotifyManager_t@@B
	mov	QWORD PTR ?staticMetaObject@NotifyManager@@2UQMetaObject@@B+8, rax
; Line 91
	lea	rax, OFFSET FLAT:?qt_meta_data_NotifyManager@@3QBIB
	mov	QWORD PTR ?staticMetaObject@NotifyManager@@2UQMetaObject@@B+16, rax
; Line 92
	lea	rax, OFFSET FLAT:?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; NotifyManager::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@NotifyManager@@2UQMetaObject@@B+24, rax
; Line 93
	mov	QWORD PTR ?staticMetaObject@NotifyManager@@2UQMetaObject@@B+32, 0
; Line 94
	mov	QWORD PTR ?staticMetaObject@NotifyManager@@2UQMetaObject@@B+40, 0
	add	rsp, 40					; 00000028H
	ret	0
??__E?staticMetaObject@NotifyManager@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'NotifyManager::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ
_TEXT	SEGMENT
??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ PROC ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 577
	mov	rax, QWORD PTR __imp_?staticMetaObject@QObject@@2UQMetaObject@@B
; Line 578
	ret	0
??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ENDP ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 48
??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ PROC ; QMetaObject::SuperData::link<&QObject::staticMetaObject>, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 600
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	call	??$staticMetaObject@$1?staticMetaObject@QObject@@2UQMetaObject@@B@QMetaObject@@SAPEBU0@XZ ; QMetaObject::staticMetaObject<&QObject::staticMetaObject>
	mov	rdx, rax
	mov	rcx, QWORD PTR __$ReturnUdt$[rsp]
	call	??0SuperData@QMetaObject@@QEAA@PEBU1@@Z	; QMetaObject::SuperData::SuperData
	mov	rax, QWORD PTR __$ReturnUdt$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??$link@$1?staticMetaObject@QObject@@2UQMetaObject@@B@SuperData@QMetaObject@@SA?AU01@XZ ENDP ; QMetaObject::SuperData::link<&QObject::staticMetaObject>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 32
this$ = 64
_t1$ = 72
?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z PROC ; NotifyManager::signalSkinChanged
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 130
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 131
	mov	QWORD PTR _a$[rsp], 0
	mov	rcx, QWORD PTR _t1$[rsp]
	call	??$addressof@$$CBVQColor@@@std@@YAPEBVQColor@@AEBV1@@Z ; std::addressof<QColor const >
	mov	QWORD PTR _a$[rsp+8], rax
; Line 132
	lea	r9, QWORD PTR _a$[rsp]
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:?staticMetaObject@NotifyManager@@2UQMetaObject@@B ; NotifyManager::staticMetaObject
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?activate@QMetaObject@@SAXPEAVQObject@@PEBU1@HPEAPEAX@Z
; Line 133
	add	rsp, 56					; 00000038H
	ret	0
?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z ENDP ; NotifyManager::signalSkinChanged
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
result$2 = 48
_o$ = 80
_c$ = 88
_id$ = 96
_a$ = 104
?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; NotifyManager::qt_static_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 68
$LN11:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 69
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 70
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 72
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN6@qt_static_:
; Line 73
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rdx, QWORD PTR [rcx+rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z ; NotifyManager::signalSkinChanged
$LN7@qt_static_:
; Line 76
	jmp	SHORT $LN5@qt_static_
$LN4@qt_static_:
	cmp	DWORD PTR _c$[rsp], 10
	jne	SHORT $LN8@qt_static_
; Line 77
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	QWORD PTR result$2[rsp], rax
; Line 80
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	lea	rcx, OFFSET FLAT:?signalSkinChanged@NotifyManager@@QEAAXAEBVQColor@@@Z ; NotifyManager::signalSkinChanged
	cmp	QWORD PTR [rax], rcx
	jne	SHORT $LN9@qt_static_
; Line 81
	mov	rax, QWORD PTR result$2[rsp]
	mov	DWORD PTR [rax], 0
$LN9@qt_static_:
$LN8@qt_static_:
$LN5@qt_static_:
; Line 86
	add	rsp, 72					; 00000048H
	ret	0
?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; NotifyManager::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@NotifyManager@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; NotifyManager::qt_metacall
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 112
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 113
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QObject@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 114
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 115
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 116
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 117
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN5@qt_metacal
; Line 118
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@NotifyManager@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; NotifyManager::qt_static_metacall
$LN5@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 120
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 121
	cmp	DWORD PTR _id$[rsp], 1
	jge	SHORT $LN7@qt_metacal
; Line 122
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 123
	mov	eax, DWORD PTR _id$[rsp]
	dec	eax
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 125
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 126
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@NotifyManager@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; NotifyManager::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@NotifyManager@@UEAAPEAXPEBD@Z PROC		; NotifyManager::qt_metacast
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 104
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 105
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 106
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_NotifyManager@@3Uqt_meta_stringdata_NotifyManager_t@@B+96
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 107
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 108
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QObject@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 109
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@NotifyManager@@UEAAPEAXPEBD@Z ENDP		; NotifyManager::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@NotifyManager@@UEBAPEBUQMetaObject@@XZ PROC	; NotifyManager::metaObject
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 99
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 100
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@NotifyManager@@2UQMetaObject@@B ; NotifyManager::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 101
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@NotifyManager@@UEBAPEBUQMetaObject@@XZ ENDP	; NotifyManager::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0SuperData@QMetaObject@@QEAA@PEBU1@@Z
_TEXT	SEGMENT
this$ = 8
mo$ = 16
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z PROC		; QMetaObject::SuperData::SuperData, COMDAT
; File d:\qt\qt5.14.2\5.14.2\msvc2017_64\include\qtcore\qobjectdefs.h
; Line 584
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR mo$[rsp]
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0SuperData@QMetaObject@@QEAA@PEBU1@@Z ENDP		; QMetaObject::SuperData::SuperData
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 136
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File f:\userdata\documents\githubrepo\project_4_qttest\_project\qtqq\qtqq\x64\debug\moc\moc_notifymanager.cpp
; Line 136
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
